name: test-integration
on:
  # pull_request:
  push:
    branches: ["main"]
  # The "workflow_dispatch" event gives us a button in GitHub's "Action" UI
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build pages
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          # cache: "npm"
          # cache-dependency-path: '**/.github/workflows/*.yml'
          # cache-dependency-path: "**/package-lock.json"
      - run: npm ci
      - run: npm run minify
      # - run: npm run assets

      - name: Build JSdocs
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./js
          output_dir: ./docs
          # config_file: conf.json
          # front_page: README.md

      - name: Upload Pages
        id: pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: .
          name: github-pages
          retention-days: 1

  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
# run the following to test locally:
# act
