name: test-integration
on:
  # pull_request:
  push:
    branches: ["main"]
  # The "workflow_dispatch" event gives us a button in GitHub's "Action" UI
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build pages
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          # cache: "npm"
          # cache-dependency-path: '**/.github/workflows/*.yml'
          # cache-dependency-path: "**/package-lock.json"
      - run: npm ci
      - run: npm run minify
      - run: npm run assets
      - run: npm run jsdoc

      - name: Upload Pages
        id: pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
          name: github-pages
          retention-days: 1
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v1
# run the following to test locally:
# act
